DATA SEGMENT 
    MSG1 DB 13,10 ,"THIS IS MESSAGE IN MSG1$"
    MSG2 DB 13,10 ,"THIS IS MESSAGE IN MSG2"
    
    DATA ENDS 
CODE SEGMENT 
    ASSUME CS : CODE , DS : DATA 
    START :
    
    MOV AX,DATA 
    MOV DS,AX 
    
    MOV DX,OFFSET MSG1 ;
    MOV AH,09H ;DISPLAY STRING FUNTION 
    INT 21H ; DISPLAY THE STRNGS AND IN UPPER CASE 
    
    MOV DX,OFFSET MSG2    ;SECOND MSG
    MOV AH,09H
    INT 21H
    
    CODE ENDS 
ENDS START 
ENDS 